--- 
ApplicationStart: 
  - 
    location: start.sh
    runas: root
    timeout: 60
BeforeInstall: 
  - 
    location: install.sh
    runas: root
    timeout: 1200
files: 
  - 
    destination: /home/ec2-user
    source: /
os: linux
permissions: 
  - 
    group: ec2-user
    mode: 744
    object: /home/ec2-user
    owner: ec2-user
    pattern: "**"
    type: 
      - directory
      - file
version: 0.0
