--- 
artifacts: 
  discard-paths: true
  files: 
    - "./*"
    - "css/*"
    - "public/css/*"
    - "public/img/*"
    - "public/js/*"
    - "public/vendor/*"
    - "public/indecx.html"
    - "vendor/jquery/*"
    - "vendor/bootstrap/**/*"
    - "vendor/font-awesome/*"
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "npm install gulp -g"
      - "npm install gulp --save-dev"
      - "echo gulp -v"
  install: 
    commands: 
      - "echo \"installing node packages\""
      - "npm install"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo \"in post build environment\""
      - gulp
  pre_build: 
    commands: 
      - "echo Nothing to do in the pre_build phase..."
version: 0.1
